### ISSUE TITLE
Fake data generator to test db

### ISSUE THREAD

**Issue by koustuvsinha** [koustuvsinha/benchmarker#6]
Need to use a fake data generator library to create and save the data for testing

**Comment by koustuvsinha** [comment]
Tried [jFairy](https://github.com/Codearte/jfairy), does not work, throwing error : 

``` java
java.io.FileNotFoundException: com/google/inject/internal/util/$Finalizer.class
            at com.google.inject.internal.util.$FinalizableReferenceQueue$DecoupledLoader.getBaseUrl(FinalizableReferenceQueue.java:269)
            at com.google.inject.internal.util.$FinalizableReferenceQueue$DecoupledLoader.loadFinalizer(FinalizableReferenceQueue.java:253)
            at com.google.inject.internal.util.$FinalizableReferenceQueue.loadFinalizer(FinalizableReferenceQueue.java:175)
            at com.google.inject.internal.util.$FinalizableReferenceQueue.<clinit>(FinalizableReferenceQueue.java:100)
            at com.google.inject.internal.util.$MapMaker$QueueHolder.<clinit>(MapMaker.java:787)
            at com.google.inject.internal.util.$MapMaker$WeakEntry.<init>(MapMaker.java:946)
            at com.google.inject.internal.util.$MapMaker$Strength$1.newEntry(MapMaker.java:312)
            at com.google.inject.internal.util.$MapMaker$StrategyImpl.newEntry(MapMaker.java:498)
            at com.google.inject.internal.util.$MapMaker$StrategyImpl.newEntry(MapMaker.java:419)
            at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2029)
            at com.google.inject.internal.Annotations$AnnotationChecker.hasAnnotations(Annotations.java:116)
            at com.google.inject.internal.Annotations.isBindingAnnotation(Annotations.java:180)
            at com.google.inject.Key.ensureIsBindingAnnotation(Key.java:366)
            at com.google.inject.Key.strategyFor(Key.java:338)
            at com.google.inject.Key.get(Key.java:272)
            at com.google.inject.assistedinject.FactoryProvider2.assistKey(FactoryProvider2.java:522)
            at com.google.inject.assistedinject.FactoryProvider2.<init>(FactoryProvider2.java:235)
            at com.google.inject.assistedinject.FactoryModuleBuilder$1.configure(FactoryModuleBuilder.java:334)
            at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
            at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
            at com.google.inject.AbstractModule.install(AbstractModule.java:118)
            at io.codearte.jfairy.FairyModule.configure(FairyModule.java:28)
            at io.codearte.jfairy.EnFairyModule.configure(EnFairyModule.java:26)
            at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
            at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
            at com.google.inject.spi.Elements.getElements(Elements.java:101)
            at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
            at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
            at com.google.inject.Guice.createInjector(Guice.java:95)
            at com.google.inject.Guice.createInjector(Guice.java:72)
            at com.google.inject.Guice.createInjector(Guice.java:62)
            at io.codearte.jfairy.Bootstrap.createFairy(Bootstrap.java:39)
            at io.codearte.jfairy.Bootstrap$Builder.build(Bootstrap.java:156)
            at io.codearte.jfairy.Bootstrap.create(Bootstrap.java:70)
            at io.codearte.jfairy.Fairy.create(Fairy.java:45)
```

**Comment by koustuvsinha** [comment]
Used [DataFactory](https://github.com/andygibson/datafactory), works quite well, but does not have a `age` field
